package com.agentplatform.runtime.model;

/**
 * 平台运行时事件类型。
 * 枚举名保持英文是为了代码稳定，但每个事件都会带中文 stage，方便前端和学习时阅读。
 */
public enum RuntimeEventType {
    RUN_STARTED,
    CONTEXT_LOADED,
    AGENT_STARTED,
    AGENT_FINISHED,
    MODEL_CALL_STARTED,
    MODEL_CALL_FINISHED,
    ANSWER_STARTED,
    ANSWER_DELTA,
    ANSWER_FINISHED,
    THINKING_STARTED,
    THINKING_DELTA,
    THINKING_FINISHED,
    TOOL_CALL_STARTED,
    TOOL_CALL_ARGS_DELTA,
    TOOL_CALL_FINISHED,
    TOOL_RESULT_STARTED,
    TOOL_RESULT_DELTA,
    TOOL_RESULT_DATA_DELTA,
    TOOL_RESULT_FINISHED,
    PLAN_CREATED,
    PLAN_STEP_STATUS_CHANGED,
    AGENT_HANDOFF,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_RESULT,
    EXTERNAL_EXECUTION_REQUIRED,
    EXTERNAL_EXECUTION_RESULT,
    RUN_STATUS_CHANGED,
    RUNTIME_WARNING,
    RUN_FINISHED,
    RUN_ERROR,
    RAW_EVENT
}
